import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { Navbar } from "@/components/blocks/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="pt-br" className="h-screen">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full overflow-y-auto`}
        data-theme="recanto-light"
      >
        <header className="w-full bg-base-100 shadow sticky px-4 top-0 right-0 left-0 z-10">
          <Navbar />
        </header>
        <main className="bg-base-100">{children}</main>
        <footer className="w-full bg-base-200 text-base-content py-4 text-center">
          <p className="text-sm">
            © {new Date().getFullYear()} Recanto do Amor Misericordioso. Todos
            os direitos reservados.
          </p>
        </footer>
      </body>
    </html>
  );
}
