import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { Navbar } from "@/components/blocks/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className="h-screen"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-base-100 antialiased h-full overflow-y-auto`}
        data-theme="recanto-light"
      >
        <header className="w-full bg-base-100 shadow sticky top-0 right-0 left-0">
          <Navbar />
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
