# Use uma imagem Node.js
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-18

# Instalação de dependências específicas do React Native
RUN npm install -g react-native-cli expo-cli

# Definir o usuário padrão
USER node
